dangerous_keywords = {
    "threat": 20,
    "attack": 30,
    "bomb": 50,
    "kill": 40,
    "explosion": 50,
    "danger": 15,
    "assault": 35,
    "murder": 50,
    "hijack": 45,
    "hostage": 40,
    "gun": 25,
    "shoot": 35,
    "terrorist": 50,
    "violence": 30,
    "dangerous": 20,
    "explode": 50,
    "destruction": 40,
    "nuclear": 60,
    "chemical": 55,
    "biological": 50,
    "cyberattack": 35,
    "sabotage": 45,
    "threaten": 20,
    "strike": 25,
    "raid": 30,
    "crash": 30,
    "hostile": 40,
    "aggression": 35,
    "militant": 45,
    "extremist": 50,
    "threatening": 25,
    "seize": 30,
    "capture": 25,
    "malware": 40,
    "ransomware": 45,
    "kidnap": 50,
    "assassinate": 50,
    "covert operation": 45,
    "snipe": 35,
    "combat": 40,
    "conflict": 30,
    "insurgency": 50,
    "extortion": 40,
    "blackmail": 45,
    "intimidate": 30,
    "violent": 40,
    "subversive": 35,
    "subversion": 40,
    "vandalism": 30,
    "riot": 35,
    "uprising": 45,
    "coup": 50,
    "overthrow": 40,
    "rebellion": 45,
    "sedition": 35,
    "anarchist": 40,
    "militia": 45,
    "guerrilla": 50,
    "bioterrorism": 55,
    "chemical warfare": 60,
    "radiation": 55,
    "dirty bomb": 60,
    "IED": 50,
    "improvised explosive device": 55,
    "car bomb": 60,
    "suicide bomber": 60,
    "nuclear threat": 70,
    "biological agent": 55,
    "chemical agent": 55,
    "hazardous material": 50,
    "dangerous substance": 45,
    "lethal": 60,
    "destructive device": 60,
    "aggressive act": 35,
    "hostile act": 40,
    "violent act": 50,
    "terror act": 60,
    "armed attack": 55,
    "cyber threat": 40,
    "digital attack": 35,
    "network intrusion": 40,
    "data breach": 35,
    "system hack": 30
}
